# Generated by Django 5.2.4 on 2025-07-22 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('catalogo', models.CharField(blank=True, max_length=100)),
                ('renglon', models.CharField(blank=True, max_length=50)),
                ('rubro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_comprada', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bienes_en_stock', models.PositiveIntegerField(default=0)),
                ('saldo_en_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.bien')),
                ('orden_de_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ordendecompra')),
            ],
        ),
    ]
