# Generated by Django 5.2.4 on 2025-07-22 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('area_persona', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('orden_de_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ordendecompra')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bien')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.entrega')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.stock')),
            ],
        ),
    ]
