# Generated by Django 5.2.4 on 2025-07-22 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_entrega_entregaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bien')),
                ('orden_de_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.ordendecompra')),
            ],
        ),
    ]
