# Generated by Django 5.2.4 on 2025-07-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_ordendecompraitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompraitem',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
