# Generated by Django 5.2.4 on 2025-07-23 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_ordendecompraitem_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
    ]
