# Generated by Django 5.2.4 on 2025-07-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_ordendecompra_fecha_ordendecompra_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
