# Generated by Django 5.2.4 on 2025-07-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_ordendecompra_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaitem',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
