# Generated by Django 5.2.4 on 2025-07-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_entregaitem_stock_delete_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaitem',
            name='orden_de_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ordendecompra'),
        ),
    ]
