# Generated by Django 5.2.4 on 2025-07-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_entregaitem_orden_de_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompraitem',
            name='renglon',
            field=models.IntegerField(default=1),
        ),
    ]
