# Generated by Django 5.2.4 on 2025-07-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_ordendecompraitem_renglon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaitem',
            name='orden_de_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrega_items', to='inventario.ordendecompra'),
        ),
    ]
