# Generated by GitHub Copilot on 2025-08-04
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0010_alter_entregaitem_orden_de_compra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordendecompra",
            name="numero",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
