# Generated by Django 5.2.5 on 2025-12-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_ordendecompra_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
