# Generated by Django 5.2.5 on 2025-12-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('frecuencia', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=10, verbose_name='Frecuencia')),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo mensual')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('POR_VENCER', 'Por vencer'), ('VENCIDO', 'Vencido'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.rubro', verbose_name='Rubro')),
            ],
        ),
    ]
