# Generated by Django 5.2.5 on 2025-12-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.rubro', verbose_name='Rubro principal'),
        ),
    ]
