# Generated by Django 5.2.5 on 2025-12-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_ordendecompra_rubro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('expediente_pago', models.CharField(blank=True, max_length=100, verbose_name='Expediente de pago')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('importe_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe pagado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inventario.servicio')),
            ],
        ),
    ]
