# Generated by Django 5.2.5 on 2025-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_serviciopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='expediente_contratacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Expediente de contratación'),
        ),
    ]
