from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('api/orden_bien_stock/<int:orden_id>/<int:bien_id>/', views.api_orden_bien_stock, name='api_orden_bien_stock'),
    path('', views.dashboard, name='dashboard'),
    path('remitos/', views.remitos_list, name='remitos_list'),
    path('rubros/', views.rubros_list, name='rubros_list'),
    path('agregar_rubro/', views.agregar_rubro, name='agregar_rubro'),
    path('rubros/<int:pk>/editar/', views.editar_rubro, name='editar_rubro'),
    path('bienes/', views.bienes_list, name='bienes_list'),
    path('agregar_bien/', views.agregar_bien, name='agregar_bien'),
    path('bienes/<int:pk>/editar/', views.editar_bien, name='editar_bien'),
    path('agregar_orden/', views.agregar_orden, name='agregar_orden'),
    # Password change URLs
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),

    path('ordenes/', views.ordenes_list, name='ordenes'),
    path('ordenes/<int:pk>/', views.orden_detalle, name='orden_detalle'),
    path('ordenes/<int:pk>/editar/', views.orden_editar, name='orden_editar'),
    path('login/', auth_views.LoginView.as_view(template_name='inventario/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/login/?logout=1'), name='logout'),
    path('entrega/nueva/', views.crear_entrega, name='crear_entrega'),
    path('entrega/<int:pk>/editar/', views.editar_entrega, name='editar_entrega'),
    path('remito/<int:pk>/pdf/', views.remito_pdf, name='remito_pdf'),
    path('remito/<int:pk>/imprimir/', views.remito_print, name='remito_print'),
    path('api/orden_bienes/<int:orden_id>/', views.api_orden_bienes, name='api_orden_bienes'),
    path('api/orden_precio/<int:orden_id>/<int:bien_id>/', views.api_orden_precio, name='api_orden_precio'),
    path('api/ordenes_con_stock_bien/<int:bien_id>/', views.api_ordenes_con_stock_bien, name='api_ordenes_con_stock_bien'),
    path('reportes/', views.reportes, name='reportes'),
    path('reportes/stock_rubro/', views.reporte_stock_rubro, name='reporte_stock_rubro'),
    path('reportes/stock_bien/', views.reporte_stock_bien, name='reporte_stock_bien'),
    path('reportes/entregas_anio/', views.reporte_entregas_anio, name='reporte_entregas_anio'),
    path('reportes/entregas_area/', views.reporte_entregas_area, name='reporte_entregas_area'),
    path('reportes/ranking_bienes/', views.reporte_ranking_bienes, name='reporte_ranking_bienes'),
    path('reportes/ranking_proveedores/', views.reporte_ranking_proveedores, name='reporte_ranking_proveedores'),
    path('reportes/personalizado/', views.reporte_personalizado, name='reporte_personalizado'),
    # Reportes de servicios
    path('reportes/servicios_estado/', views.reporte_servicios_estado, name='reporte_servicios_estado'),
    path('reportes/servicios_proveedor/', views.reporte_servicios_proveedor, name='reporte_servicios_proveedor'),
    path('reportes/servicios_rubro/', views.reporte_servicios_rubro, name='reporte_servicios_rubro'),
    path('reportes/costos_servicios/', views.reporte_costos_servicios, name='reporte_costos_servicios'),
    path('reportes/servicios_pendientes/', views.reporte_servicios_pendientes, name='reporte_servicios_pendientes'),
    path('reportes/servicios_pendientes/realizar_pago/<int:pago_id>/', views.realizar_pago, name='realizar_pago'),
    path('auditoria/', views.audit_log_list, name='audit_log'),
    # URLs para servicios
    path('servicios/', views.servicios_list, name='servicios_list'),
    path('agregar_servicio/', views.agregar_servicio, name='agregar_servicio'),
    path('servicios/<int:pk>/editar/', views.editar_servicio, name='editar_servicio'),
    path('servicios/<int:pk>/', views.servicio_detalle, name='servicio_detalle'),
    path('servicios/<int:pago_id>/marcar_pagado/', views.marcar_pago_pagado, name='marcar_pago_pagado'),
    path('servicios/<int:pk>/renovar/', views.renovar_servicio, name='renovar_servicio'),
]
